// <auto-generated />
using System;
using DesafioCient.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DesafioCient.Migrations
{
    [DbContext(typeof(DesafioCientContext))]
    [Migration("20220325044742_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("DesafioCient.Models.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnName("Cnpj")
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.Property<DateTime>("Criado")
                        .HasColumnName("Criado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnName("Email")
                        .HasColumnType("TEXT")
                        .HasMaxLength(30);

                    b.Property<DateTime?>("Excluido")
                        .HasColumnName("Excluido")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstituicaoApoio")
                        .HasColumnName("InstituicaoApoio")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("Modificado")
                        .HasColumnName("Modificado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("Nome")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("Telefone")
                        .HasColumnName("Telefone")
                        .HasColumnType("TEXT")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("Empresa");
                });
#pragma warning restore 612, 618
        }
    }
}
